name: deploy static.hasanjoldic.com

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: garygrossgarten/github-action-ssh@release
        with:
          command: | 
            if cd /root/apps/static.hasanjoldic.com; then git pull; 
            else git clone git@github.com:hasanjoldic/static.hasanjoldic.com.git /root/apps/static.hasanjoldic.com; fi
            cd /root/apps/static.hasanjoldic.com && docker-compose up --detach
          host: static.hasanjoldic.com
          username: root
          privateKey: ${{ secrets.HASAN_JOLDIC_COM_PRIVATE_KEY }}
